### ISSUE TITLE
GCD branch merger master issue - all repositories

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1011]
Master checklist:

- [x] Rebase and Prepare SDK GCD branch for merger - version 8.2.0 - PR: https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/pull/210
- [ ] Merge and release version 8.2.0 SDK
- [x] Rebase and Prepare WebServices GCD branch for merger - PR: https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pull/251
- [ ] Update server version to new release (7.1.0?)
- [ ] Retarget SDK to released version
- [ ] Merge and release WebServices 7.1.0
- [ ] Release docker containers WebServices 7.1.0
- [ ] Rebase and Prepare IME GCD branch for merger
- [ ] Retarget IME to released SDK
- [ ] Verify IME new version (10.0.0.0)
- [ ] Merge IME into development
- [ ] Create RC
- [ ] Validation testing
- [ ] Release version 10
- [ ] Retarget GCD plugin SDK
- [ ] Release GCD plugin new version
